import { copyFileSync, existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import {
  atomicWrite,
  canonicalJson,
  ensureDir,
  redactRecord,
  repoRoot,
  sha256,
  sha256Object,
  YhtError,
} from './common.mjs'
import { resolveCommand } from './system.mjs'

function envQuote(value) {
  const text = String(value ?? '')
  if (/\r|\n|\0/.test(text)) throw new YhtError('Environment values cannot contain control characters', { code: 'ENV_VALUE_INVALID' })
  return `"${text.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`
}

function sqlString(value) {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'boolean') return value ? '1' : '0'
  if (/^(true|false)$/.test(String(value))) return String(value) === 'true' ? '1' : '0'
  return `'${String(value).replaceAll('\\', '\\\\').replaceAll("'", "''")}'`
}

function renderDeploySql(deployDatabase, compatibilityMode) {
  const statements = [
    '-- Generated by yhtctl. Values marked sensitive are never emitted in recommended mode.',
    'START TRANSACTION;',
  ]
  for (const [key, item] of Object.entries(deployDatabase).sort(([a], [b]) => a.localeCompare(b))) {
    if (item.sensitive) {
      if (compatibilityMode) statements.push(`-- compatibility-only sensitive key omitted from generated SQL: ${key}`)
      continue
    }
    if (item.authority !== 'deploy_db') continue
    statements.push(
      'INSERT INTO `system_deploy_config` '
      + '(`config_key`,`config_value`,`group_key`,`display_name`,`value_type`,`sensitive`,`client_visible`,`editable`,`remark`,`is_deleted`) '
      + `VALUES (${sqlString(key)},${sqlString(item.value)},'',${sqlString(key)},'string',0,0,1,'yhtctl profile override',0) `
      + 'ON DUPLICATE KEY UPDATE `config_value`=VALUES(`config_value`),`remark`=VALUES(`remark`),`is_deleted`=0;',
    )
  }
  statements.push('COMMIT;', '')
  return statements.join('\n')
}

function renderBrandSql(brandDatabase) {
  const entries = Object.entries(brandDatabase).sort(([a], [b]) => a.localeCompare(b))
  const columns = ['id', ...entries.map(([column]) => column)]
  const values = ['1', ...entries.map(([, value]) => sqlString(value))]
  const updates = entries.map(([column]) => `\`${column}\`=VALUES(\`${column}\`)`)
  return [
    '-- Generated public brand configuration. Contains no secrets.',
    'START TRANSACTION;',
    `INSERT INTO \`system_brand_config\` (${columns.map((column) => `\`${column}\``).join(',')})`,
    `VALUES (${values.join(',')})`,
    `ON DUPLICATE KEY UPDATE ${updates.join(',')};`,
    'COMMIT;',
    '',
  ].join('\n')
}

function serverName(url) {
  return new URL(url).hostname
}

function tlsLines(profile, authority) {
  if (profile.tls.mode !== 'existing-files') return ['  listen 80;']
  const cert = profile.tls.certificateRef.replace(/^file:\/\//, profile.deployment.paths.configRoot + '/')
  const keyRecord = authority.records.find((record) => record.profilePath === 'tls.privateKeySecretRef')
  if (!keyRecord) throw new YhtError('TLS private key secret was not materialized', { code: 'TLS_PRIVATE_KEY_MISSING' })
  const key = keyRecord.value
  return [
    '  listen 443 ssl http2;',
    `  ssl_certificate ${cert};`,
    `  ssl_certificate_key ${key};`,
  ]
}

function renderNginx(profile, authority) {
  const { endpoints, paths, ports } = profile.deployment
  const listen = tlsLines(profile, authority).join('\n')
  return `# Generated by yhtctl. Validate with nginx -t before reload.
server {
${listen}
  server_name ${serverName(endpoints.apiBaseUrl)};
  location / { proxy_pass http://127.0.0.1:${ports.api}; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
}
server {
${listen}
  server_name ${serverName(endpoints.manageBaseUrl)};
  root ${paths.installRoot}/current/manage-admin;
  location / { try_files $uri $uri/ /index.html; }
}
server {
${listen}
  server_name ${serverName(endpoints.userBaseUrl)};
  root ${paths.installRoot}/current/pc-admin;
  location / { try_files $uri $uri/ /index.html; }
}
server {
${listen}
  server_name ${serverName(endpoints.h5BaseUrl)};
  root ${paths.installRoot}/current/h5;
  location / { try_files $uri $uri/ /index.html; }
}
server {
${listen}
  server_name ${serverName(endpoints.websiteBaseUrl)};
  location / { proxy_pass http://127.0.0.1:${ports.website}; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
  location /customer-assets/ { alias ${paths.configRoot}/assets/; try_files $uri =404; }
}
`
}

function renderApiService(profile, executables) {
  const { paths } = profile.deployment
  return `[Unit]
Description=Yihetong API
After=network-online.target mysql.service redis.service
Wants=network-online.target

[Service]
Type=simple
User=yihetong
Group=yihetong
WorkingDirectory=${paths.installRoot}/current/server
EnvironmentFile=${paths.configRoot}/runtime.env
ExecStart=${executables.java} -jar ${paths.installRoot}/current/server/esign.jar --spring.config.additional-location=file:${paths.configRoot}/application.yml --logging.file.path=${paths.dataRoot}/logs
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${paths.dataRoot} ${paths.backupRoot}

[Install]
WantedBy=multi-user.target
`
}

function renderWebsiteService(profile, executables) {
  const { paths, ports, endpoints } = profile.deployment
  return `[Unit]
Description=Yihetong Website
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=yihetong
Group=yihetong
WorkingDirectory=${paths.installRoot}/current/website
Environment=NODE_ENV=production
Environment=PORT=${ports.website}
Environment=HOSTNAME=127.0.0.1
Environment=YHT_API_BASE=http://127.0.0.1:${ports.api}
Environment=BRAND_CONFIG_URL=http://127.0.0.1:${ports.api}/api/v1/brand-config/active
Environment=YHT_USER_PORTAL_URL=${endpoints.userBaseUrl}
Environment=YHT_MANAGE_PORTAL_URL=${endpoints.manageBaseUrl}
Environment=YHT_H5_PORTAL_URL=${endpoints.h5BaseUrl}
Environment=PATH=${path.posix.dirname(executables.node)}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/bin/bash ${paths.installRoot}/current/website/start-website.sh
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${paths.dataRoot}/website-cache

[Install]
WantedBy=multi-user.target
`
}

function renderLicenseRefreshService(profile) {
  const { paths } = profile.deployment
  return `[Unit]
Description=Yihetong commercial License lease refresh
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
Group=root
ExecStart=${paths.installRoot}/current/tooling/yhtctl license refresh --profile ${paths.configRoot}/customer-profile.yaml --secrets ${paths.configRoot}/secrets.refs.yaml --activation-dir ${paths.configRoot}/commercial
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${paths.configRoot}/commercial ${paths.dataRoot}/commercial
`
}

function renderLicenseRefreshTimer(profile) {
  return `[Unit]
Description=Refresh Yihetong commercial License lease

[Timer]
OnBootSec=2min
OnUnitActiveSec=${profile.commercialAuthorization.leaseRefreshSeconds}s
RandomizedDelaySec=30s
Persistent=true
Unit=yihetong-license-refresh.service

[Install]
WantedBy=timers.target
`
}

function renderExternalActions(actions) {
  const lines = ['# External Actions', '', '| ID | Platform | State | Owner | Action | Verification |', '| --- | --- | --- | --- | --- | --- |']
  for (const action of actions) {
    const clean = (value) => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ')
    lines.push(`| ${clean(action.id)} | ${clean(action.platform)} | ${clean(action.state)} | ${clean(action.owner)} | ${clean(action.action)} | ${clean(action.verification)} |`)
  }
  lines.push('', 'Platform actions are separate from local installation acceptance. `user-final-required` is not a local pass.', '')
  return lines.join('\n')
}

export function renderConfiguration({ profile, authority, outputDir, sourceRoot = repoRoot, drift = null, authorizationFiles = {}, additionalEnvironment = {} }) {
  ensureDir(outputDir, 0o750)
  const compatibilityMode = profile.security.sensitiveDbCompatibilityMode
  const executables = {
    java: process.platform === 'linux' ? (resolveCommand('java') || '/usr/bin/java') : '/usr/bin/java',
    node: process.platform === 'linux' ? (resolveCommand('node') || '/usr/bin/node') : '/usr/bin/node',
  }
  const runtimeEnvironment = { ...authority.environment, ...additionalEnvironment }
  const environmentText = `${Object.entries(runtimeEnvironment)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `${key}=${envQuote(value)}`)
    .join('\n')}\n`
  const outputs = {
    'runtime.env': { content: environmentText, mode: 0o600, sensitive: true },
    'system-deploy-config.sql': { content: renderDeploySql(authority.deployDatabase, compatibilityMode), mode: 0o640 },
    'brand-config.sql': { content: renderBrandSql(authority.brandDatabase), mode: 0o640 },
    'nginx/yihetong.conf': { content: renderNginx(profile, authority), mode: 0o640 },
    'systemd/yihetong-api.service': { content: renderApiService(profile, executables), mode: 0o640 },
    'systemd/yihetong-website.service': { content: renderWebsiteService(profile, executables), mode: 0o640 },
    'systemd/yihetong-license-refresh.service': { content: renderLicenseRefreshService(profile), mode: 0o640 },
    'systemd/yihetong-license-refresh.timer': { content: renderLicenseRefreshTimer(profile), mode: 0o640 },
    'build-inputs.env': {
      content: `${Object.entries(authority.buildInputs).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}=${envQuote(value)}`).join('\n')}\n`,
      mode: 0o640,
    },
    'external-actions.md': { content: renderExternalActions(profile.externalActions), mode: 0o640 },
    ...authorizationFiles,
  }
  const applicationTemplate = path.join(sourceRoot, 'deploy', 'backend', 'application-template-prod.example.yml')
  if (existsSync(applicationTemplate)) {
    outputs['application.yml'] = { content: readFileSync(applicationTemplate, 'utf8'), mode: 0o640 }
  }
  for (const [relative, content] of Object.entries(authority.restrictedFiles || {})) {
    outputs[relative] = { content, mode: 0o600, sensitive: true }
  }
  const manifestEntries = []
  for (const [relative, descriptor] of Object.entries(outputs)) {
    const target = path.join(outputDir, ...relative.split('/'))
    atomicWrite(target, descriptor.content, descriptor.mode)
    manifestEntries.push({
      path: relative,
      bytes: Buffer.byteLength(descriptor.content, 'utf8'),
      sha256: sha256(descriptor.content),
      mode: descriptor.mode.toString(8).padStart(4, '0'),
      sensitive: Boolean(descriptor.sensitive),
    })
  }
  const plan = {
    apiVersion: 'yht.io/v1',
    kind: 'RenderedConfigurationPlan',
    customerCode: profile.metadata.customerCode,
    profileRevision: profile.metadata.profileRevision,
    profileFingerprint: sha256Object(profile),
    authorityFingerprint: authority.authorityFingerprint,
    sensitiveDbCompatibilityMode: compatibilityMode,
    additionalEnvironmentKeys: Object.keys(additionalEnvironment).sort(),
    runtimeExecutables: executables,
    providerScope: ['aliyun-oss'],
    records: authority.records.map(redactRecord),
    drift,
    outputs: manifestEntries,
  }
  plan.planDigest = sha256Object(plan)
  atomicWrite(path.join(outputDir, 'CONFIG_PLAN.json'), canonicalJson(plan), 0o640)
  manifestEntries.push({
    path: 'CONFIG_PLAN.json',
    bytes: Buffer.byteLength(canonicalJson(plan), 'utf8'),
    sha256: sha256(canonicalJson(plan)),
    mode: '0640',
    sensitive: false,
  })
  atomicWrite(path.join(outputDir, 'RENDER_MANIFEST.json'), canonicalJson({ version: 1, files: manifestEntries }), 0o640)
  return { plan, manifestEntries, outputDir: path.resolve(outputDir) }
}
