apiVersion: yht.io/v1
kind: SecretReferences
mode: recommended
refs:
  database.password:
    provider: env
    key: YHT_SECRET_DATABASE_PASSWORD
    required: true
  database.migration-password:
    provider: env
    key: YHT_SECRET_DATABASE_MIGRATION_PASSWORD
    required: true
  database.backup-password:
    provider: env
    key: YHT_SECRET_DATABASE_BACKUP_PASSWORD
    required: true
  redis.user.password:
    provider: env
    key: YHT_SECRET_USER_REDIS_PASSWORD
    required: true
  redis.default.password:
    provider: env
    key: YHT_SECRET_DEFAULT_REDIS_PASSWORD
    required: true
  mini-program.app-secret:
    provider: prompt
    label: Mini program application secret
    required: true
